package com.emm.gema.core.ui

enum class GTextStyle {
    TITLE_MEDIUM,
    TITLE_MEDIUM_EMPHASIS,
    NUMERAL,
    BODY_LARGE,
    BODY_MEDIUM,
    BODY_SMALL,
    BODY_SMALL_EMPHASIS,
    BODY_SMALL_TABULAR,
    LABEL_LARGE_EMPHASIS,
    LABEL_SMALL,
}
