package com.emm.gema.core.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF3F6836)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE4EFD9)
val onPrimaryContainerLight = Color(0xFF285020)
val errorLight = Color(0xFFB42318)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFDE1DF)
val onErrorContainerLight = Color(0xFF8C1D13)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF17181A)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF17181A)
val surfaceVariantLight = Color(0xFFDFE4D7)
val onSurfaceVariantLight = Color(0xFF6E7075)
val outlineLight = Color(0xFFC9C9C5)
val outlineVariantLight = Color(0xFFE6E6E3)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF17181A)
val inverseOnSurfaceLight = Color(0xFFEFF2E8)
val inversePrimaryLight = Color(0xFFA5D396)
val surfaceDimLight = Color(0xFFD8DBD2)
val surfaceBrightLight = Color(0xFFF8FBF1)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F6F4)
val surfaceContainerLight = Color(0xFFECEFE5)
val surfaceContainerHighLight = Color(0xFFEDEDEA)
val surfaceContainerHighestLight = Color(0xFFE1E4DA)

val warningContainerLight = Color(0xFFFBF4E1)
val onWarningContainerLight = Color(0xFF5C4A12)

val primaryDark = Color(0xFFA5D396)
val onPrimaryDark = Color(0xFF11380B)
val primaryContainerDark = Color(0xFF2C4A27)
val onPrimaryContainerDark = Color(0xFFC0EFB0)
val errorDark = Color(0xFFF4A29A)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF5C1E19)
val onErrorContainerDark = Color(0xFFFDE1DF)
val backgroundDark = Color(0xFF191A1C)
val onBackgroundDark = Color(0xFFECECEA)
val surfaceDark = Color(0xFF191A1C)
val onSurfaceDark = Color(0xFFECECEA)
val surfaceVariantDark = Color(0xFF43483F)
val onSurfaceVariantDark = Color(0xFFA0A2A8)
val outlineDark = Color(0xFF55575D)
val outlineVariantDark = Color(0xFF34353A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFECECEA)
val inverseOnSurfaceDark = Color(0xFF2E322B)
val inversePrimaryDark = Color(0xFF3F6836)
val surfaceDimDark = Color(0xFF11140F)
val surfaceBrightDark = Color(0xFF363A34)
val surfaceContainerLowestDark = Color(0xFF0B0F0A)
val surfaceContainerLowDark = Color(0xFF222326)
val surfaceContainerDark = Color(0xFF1D211B)
val surfaceContainerHighDark = Color(0xFF2C2D31)
val surfaceContainerHighestDark = Color(0xFF32362F)

val warningContainerDark = Color(0xFF3A3222)
val onWarningContainerDark = Color(0xFFEAD79C)
